substitutions:
  devicename: dualbme_1
  upper_devicename: DualBME_1
  friendly_name: Dual BME 1

<<: !include base_config.yaml

i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a

text_sensor:
  - platform: version
    name: ${friendly_name} ESPHome Version

sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal Strength
    update_interval: 60s

  - platform: bme280
    temperature:
      name: "${friendly_name} Inside Temperature"
    pressure:
      name: "${friendly_name} Inside Pressure"
    humidity:
      name: "${friendly_name} Inside Humidity"
    update_interval: 60s
    address: 0x77
  - platform: bme280
    temperature:
      name: "${friendly_name} Outside Temperature"
    pressure:
      name: "${friendly_name} Outside Pressure"
    humidity:
      name: "${friendly_name} Outside Humidity"
    update_interval: 60s
    address: 0x76
