substitutions:
  prefix: espico
  location: espico
  devicename: ${prefix}
  upper_devicename: ${location} Aquarium
  friendly_name: ${location} Aquarium
  short_name: ${prefix} Aquarium

globals:
  - id: tcomp
    type: float
    restore_value: no
    initial_value: '21.0'

# <<: !include esp32_base_config.yaml
esphome:
  name: esp_${devicename}
  platform: ESP32
  board: esp32doit-devkit-v1
  platformio_options:
    lib_deps: NeoPixelBus@2.6.0
  on_boot:
    priority: 260
    then:
      # enable clock effect after boot
      - light.turn_on: 
          id: light_main
          brightness: 100%
          red: 0%
          green: 2%
          blue: 100%
          white: 40%
      - stepper.set_speed:
          id: ato_feed
          speed: 80 steps/s
      - stepper.report_position:
          id: ato_feed
          position: 0
      - stepper.set_target:
          id: ato_feed
          target: 1000

# red lit green
# green lit red
# blue lit blue

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wpa_pass
    - ssid: !secret wifi_ssid_ha
      password: !secret wpa_pass
  domain: .garbled.net

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${short_name} FB Hotspot"
    password: !secret portal_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# font:
#   - file: 'arial_narrow_7.ttf'
#     id: thin_font
#     size: 12
#     # glyphs: "0123456789°%.Alarm:"

i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: True
  # - id: bus_b
  #   sda: 18
  #   scl: 19
  #   scan: True
  
text_sensor:
  - platform: version
    name: ${friendly_name} ESPHome Version

light:
  - platform: neopixelbus
    type: GRBW
    pin: 19
    num_leds: 136
    name: "NeoPixel Light"
    variant: SK6812
    method: ESP32_I2S_1
    restore_mode: ALWAYS_ON
    id: light_main

binary_sensor:
  - platform: gpio
    pin: 15
    name: "Water Level"
    #device_class: window

stepper:
  - platform: a4988
    id: ato_feed
    step_pin: 23
    dir_pin: 18
    max_speed: 250 steps/s
    sleep_pin: 4
